<?php

namespace AppBundle\Repository;

/**
 * NurserySelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NurserySelectionRepository extends \Doctrine\ORM\EntityRepository
{
}
