<?php

namespace AppBundle\Repository;

/**
 * NurseryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NurseryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
