version: "3.5"

services:

  maria:
    restart: always
    image: mariadb:latest
    container_name: ${PROJECT}_maria
    command: mysqld --innodb-flush-method=O_DSYNC --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROJECT}
      MYSQL_DATABASE_TEST: ${PROJECT}_test
      MYSQL_USER: ${PROJECT}
      MYSQL_PASSWORD: ${PROJECT}
    networks:
      project_network:
        ipv4_address: 172.29.0.100
    volumes:
      - mysql_data:/var/lib/mysql
      - .docker/maria/conf:/etc/mysql/conf.d
      - .docker/maria/init:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
#    ports:
#      - 3308:3306

  api:
    restart: always
    container_name: ${PROJECT}_api
    build:
      context: .
    volumes:
      - user_upload:/app/web/maps
      - .docker/import:/app/var/import
    networks:
      project_network:
        ipv4_address: 172.29.0.20
    depends_on:
      - maria
    ports:
      - 8899:8000

volumes:
  mysql_data:
    driver: local
  user_upload:
    driver: local

networks:
  project_network:
    name: ${PROJECT}
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
